### ISSUE TITLE
why do you use abnormal data to train?

### ISSUE THREAD

**Issue by YohannaYin** [houssamzenati/Efficient-GAN-Anomaly-Detection#20]
when I want to use my self dataset,I found your model just use abnormal dataset of KDD99 to train.But  When I read some other paper, they said when they use  GAN model to do abnormal detection ,they just use normal dataset to train,not abnormal dataset. Could you answer my question?

**Comment by Minqi824** [comment]
@YohannaYin . Great question and I agree with you. Normal data are used for constructing the architecture so that the model cannot correctly reconstructed the anomaly samples and thus generates a relatively higher loss (anomaly score).
Hope the author could answer this question. @houssamzenati @bruno-31

**Comment by Minqi824** [comment]
@YohannaYin . I notice that there is a sentence in the paper "_Adversarially Learned Anomaly Detection
Houssam_": "**Due to the high proportion of outliers in the KDD dataset, “normal” data are treated as anomalies and the 20% of samples with the highest anomaly scores A(x) are classified as anomalies (positive class)**."

Therefore the anomaly samples are treated as normal samples and feeded into the model. Should this be the answer?

**Comment by houssamzenati** [comment]
Apologies for answering so late and many thanks @jmq19950824 for your reply, indeed we follow the setup of the DAGMM paper so it is as you said
